language: node_js

node_js:
  - '10'

before_script:
  - npm install

script:
  - npm run lint
  - CI= npm run test:ci

after_success:
  - codecov --token="$CODECOV_TOKEN"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
  only:
    - master
    - next
