language: node_js

node_js:
  - '14'
  - '12'
  - '10'
  - 'node'
  - 'lts/*'

install: npm install

script:
  - npm run lint
  - npm run test:ci

after_success:
  - codecov --token="$CODECOV_TOKEN"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
  only:
    - main
    - next
    - dev
    - beta
