// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Constructable<T> = new (...args: any[]) => T;

/**
 * Base class for all errors generated by the script
 */
export default class TwilioError extends Error {
  constructor(msg?: string) {
    super(msg);

    Object.setPrototypeOf(this, TwilioError.prototype);
  }

  /**
   * Returns whether this is the instance of the passed class
   * @param err the error class to test for
   */
  public instanceOf = <T extends Error>(err: Constructable<T>): boolean => {
    // eslint-disable-next-line consistent-this, @typescript-eslint/no-this-alias
    let klass = this;
    while (klass && klass !== Object.prototype) {
      if (!klass || !klass.constructor || !klass.constructor.name) {
        return false;
      }

      if (err.name === klass.constructor.name) {
        return true;
      }

      klass = Object.getPrototypeOf(klass);
    }

    return false;
  };
}
