/**
 * Base class for all errors generated by the script
 */
export default class TwilioError extends Error {
  constructor(msg?: string) {
    super(msg);

    Object.setPrototypeOf(this, TwilioError.prototype);
  }
}
